export const siteConfig = {
    siteUrl: "https://christopher-nafrere.fr",
    siteName: "Portfolio Christopher Nafrere",
    title: "Christopher Nafrere | Développeur Fullstack Next.js & NestJS",
    description:
        "Portfolio de Christopher Nafrere, développeur fullstack TypeScript (Next.js, NestJS, PostgreSQL, Docker, AWS), disponible en freelance, CDD et CDI en Ile-de-France, Paris, Yvelines, Epone, Mantes-la-Jolie et Mantes-la-Ville.",
    locale: "fr_FR",
    author: "Christopher Nafrere",
    keywords: [
        "Christopher Nafrere",
        "christopher nafrere",
        "Chris Nafrere",
        "C Nafrere",
        "portfolio Christopher Nafrere",
        "developpeur fullstack",
        "developpeur web",
        "developpeur TypeScript",
        "freelance",
        "mission freelance",
        "CDD developpeur",
        "CDI developpeur",
        "developpeur IDF",
        "developpeur Ile de France",
        "developpeur Paris",
        "developpeur Yvelines",
        "developpeur Yveline",
        "developpeur Epone",
        "developpeur Epones",
        "developpeur Mantes la Jolie",
        "developpeur Mantes la jolies",
        "developpeur Mantes la Ville",
        "TypeScript",
        "Next.js",
        "NestJS",
        "PostgreSQL",
        "Docker",
        "AWS",
    ],
    social: {
        github: "https://github.com/christophernafrere",
        linkedin: "https://www.linkedin.com/in/christopher-nafrere",
    },
};

export const personJsonLd = {
    "@context": "https://schema.org",
    "@type": "Person",
    name: siteConfig.author,
    alternateName: ["christopher nafrere", "Chris Nafrere", "C Nafrere"],
    url: siteConfig.siteUrl,
    sameAs: [siteConfig.social.github, siteConfig.social.linkedin],
    jobTitle: "Développeur Fullstack",
    description: siteConfig.description,
    homeLocation: {
        "@type": "Place",
        name: "Mantes-la-Ville, Yvelines, Ile-de-France",
    },
    areaServed: [
        { "@type": "Place", name: "Ile-de-France" },
        { "@type": "Place", name: "Paris" },
        { "@type": "Place", name: "Yvelines" },
        { "@type": "Place", name: "Epone" },
        { "@type": "Place", name: "Mantes-la-Jolie" },
        { "@type": "Place", name: "Mantes-la-Ville" },
    ],
    knowsAbout: [
        "Freelance",
        "CDD",
        "CDI",
        "TypeScript",
        "Next.js",
        "NestJS",
        "PostgreSQL",
        "Docker",
        "AWS",
    ],
};
